services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun -DAPP_PROFILE=local
    stdin_open: true  # Keep stdin open even if not attached
    tty: true         # Allocate a pseudo-TTY
