spring:
  application:
    name: jm0524
  datasource:
    url: jdbc:postgresql://db:5432/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

logging:
  level:
    org.springframework: WARN
    com.zaxxer.hikari: ERROR
    org.hibernate: ERROR